In [49]:
import pandas as pd
import numpy as np
import re
import jinja2
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import RandomForestClassifier

In [50]:
b = pd.read_csv(r"C:\Users\ASUS\OneDrive\Documents\Rakamin\Project\Data Set\bureau.csv", 
                 encoding="latin1")  # bisa ganti 'cp1252' kalau latin1 error
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)
b.head()

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.00,-153.00,NaN,0,91323.00,0.00,NaN,0.00,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.00,NaN,NaN,0,225000.00,171342.00,NaN,0.00,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.00,NaN,NaN,0,464323.50,NaN,NaN,0.00,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.00,NaN,NaN,0.00,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.00,NaN,77674.50,0,2700000.00,NaN,NaN,0.00,Consumer credit,-21,NaN

In [51]:
bb = pd.read_csv(r"C:\Users\ASUS\OneDrive\Documents\Rakamin\Project\Data Set\bureau_balance.csv", 
                  encoding="latin1")  # bisa ganti 'cp1252' kalau latin1 error
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)
bb.head()

   SK_ID_BUREAU  MONTHS_BALANCE STATUS
0       5715448               0      C
1       5715448              -1      C
2       5715448              -2      C
3       5715448              -3      C
4       5715448              -4      C

In [52]:
ccb = pd.read_csv(r"C:\Users\ASUS\OneDrive\Documents\Rakamin\Project\Data Set\credit_card_balance.csv", 
                  encoding="latin1")  # bisa ganti 'cp1252' kalau latin1 error
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)
ccb.head()

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.97,135000,0.00,877.50,0.00,877.50,1700.33,1800.00,1800.00,0.00,0.00,0.00,0.00,1,0.00,1.00,35.00,Active,0,0
1,2582071,363914,-1,63975.56,45000,2250.00,2250.00,0.00,0.00,2250.00,2250.00,2250.00,60175.08,64875.56,64875.56,1.00,1,0.00,0.00,69.00,Active,0,0
2,1740877,371185,-7,31815.22,450000,0.00,0.00,0.00,0.00,2250.00,2250.00,2250.00,26926.42,31460.08,31460.08,0.00,0,0.00,0.00,30.00,Active,0,0
3,1389973,337855,-4,236572.11,225000,2250.00,2250.00,0.00,0.00,11795.76,11925.00,11925.00,224949.29,233048.97,233048.97,1.00,1,0.00,0.00,10.00,Active,0,0
4,1891521,126868,-1,453919.46,450000,0.00,11547.00,0.00,11547.00,22924.89,27000.00,27000.00,443044.40,453919.46,453919.46,0.00,1,0.00,1.00,101.00,Active,0,0

In [53]:
ip = pd.read_csv(r"C:\Users\ASUS\OneDrive\Documents\Rakamin\Project\Data Set\installments_payments.csv", 
                 encoding="latin1")  # bisa ganti 'cp1252' kalau latin1 error
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)
ip.head()

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
0,1054186,161674,1.00,6,-1180.00,-1187.00,6948.36,6948.36
1,1330831,151639,0.00,34,-2156.00,-2156.00,1716.53,1716.53
2,2085231,193053,2.00,1,-63.00,-63.00,25425.00,25425.00
3,2452527,199697,1.00,3,-2418.00,-2426.00,24350.13,24350.13
4,2714724,167756,1.00,2,-1383.00,-1366.00,2165.04,2160.59

In [54]:
pcb = pd.read_csv(r"C:\Users\ASUS\OneDrive\Documents\Rakamin\Project\Data Set\POS_CASH_balance.csv", 
                  encoding="latin1")  # bisa ganti 'cp1252' kalau latin1 error
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)
pcb.head()

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,1803195,182943,-31,48.00,45.00,Active,0,0
1,1715348,367990,-33,36.00,35.00,Active,0,0
2,1784872,397406,-32,12.00,9.00,Active,0,0
3,1903291,269225,-35,48.00,42.00,Active,0,0
4,2341044,334279,-35,36.00,35.00,Active,0,0

In [55]:

pa = pd.read_csv(r"C:\Users\ASUS\OneDrive\Documents\Rakamin\Project\Data Set\previous_application.csv", 
                  encoding="latin1")  # bisa ganti 'cp1252' kalau latin1 error
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)
pa.head()

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.43,17145.00,17145.00,0.00,17145.00,SATURDAY,15,Y,1,0.00,0.18,0.87,XAP,Approved,-73,Cash through the bank,XAP,NaN,Repeater,Mobile,POS,XNA,Country-wide,35,Connectivity,12.00,middle,POS mobile with interest,365243.00,-42.00,300.00,-42.00,-37.00,0.00
1,2802425,108129,Cash loans,25188.62,607500.00,679671.00,NaN,607500.00,THURSDAY,11,Y,1,NaN,NaN,NaN,XNA,Approved,-164,XNA,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Contact center,-1,XNA,36.00,low_action,Cash X-Sell: low,365243.00,-134.00,916.00,365243.00,365243.00,1.00
2,2523466,122040,Cash loans,15060.74,112500.00,136444.50,NaN,112500.00,TUESDAY,11,Y,1,NaN,NaN,NaN,XNA,Approved,-301,Cash through the bank,XAP,"Spouse, partner",Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.00,high,Cash X-Sell: high,365243.00,-271.00,59.00,365243.00,365243.00,1.00
3,2819243,176158,Cash loans,47041.33,450000.00,470790.00,NaN,450000.00,MONDAY,7,Y,1,NaN,NaN,NaN,XNA,Approved,-512,Cash through the bank,XAP,NaN,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.00,middle,Cash X-Sell: middle,365243.00,-482.00,-152.00,-182.00,-177.00,1.00
4,1784265,202054,Cash loans,31924.40,337500.00,404055.00,NaN,337500.00,THURSDAY,9,Y,1,NaN,NaN,NaN,Repairs,Refused,-781,Cash through the bank,HC,NaN,Repeater,XNA,Cash,walk-in,Credit and cash offices,-1,XNA,24.00,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:

ss = pd.read_csv(r"C:\Users\ASUS\OneDrive\Documents\Rakamin\Project\Data Set\sample_submission.csv", 
                  encoding="latin1")  # bisa ganti 'cp1252' kalau latin1 error
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)
ss.head()

   SK_ID_CURR  TARGET
0      100001    0.50
1      100005    0.50
2      100013    0.50
3      100028    0.50
4      100038    0.50

In [57]:
pd.set_option('display.max_rows', None)
def data_overview(b):
    overview = pd.DataFrame({
        "Column": b.columns,
        "Data Type": b.dtypes.astype(str).values,
        "Total Rows": len(b),
        "Missing": b.isnull().sum().values,
        "% Missing": (b.isnull().mean().values * 100).round(2),
        "Unique Values": b.nunique().values,
        "Unique Sample": [
            [x.item() if hasattr(x, "item") else x for x in b[col].dropna().unique()[:5]]
            for col in b.columns]
    })
    
    overview = overview.reset_index(drop=True)
    return overview

data_overview(b)

,Column,Data Type,Total Rows,Missing,% Missing,Unique Values,Unique Sample
0,SK_ID_CURR,int64,1716428,0,0.00,305811,"[215354, 162297, 402440, 238881, 222183]"
1,SK_ID_BUREAU,int64,1716428,0,0.00,1716428,"[5714462, 5714463, 5714464, 5714465, 5714466]"
2,CREDIT_ACTIVE,object,1716428,0,0.00,4,"[Closed, Active, Sold, Bad debt]"
3,CREDIT_CURRENCY,object,1716428,0,0.00,4,"[currency 1, currency 2, currency 4, currency 3]"
4,DAYS_CREDIT,int64,1716428,0,0.00,2923,"[-497, -208, -203, -629, -273]"
5,CREDIT_DAY_OVERDUE,int64,1716428,0,0.00,942,"[0, 2603, 6, 30, 2156]"
6,DAYS_CREDIT_ENDDATE,float64,1716428,105553,6.15,14096,"[-153.0, 1075.0, 528.0, 1197.0, 27460.0]"
7,DAYS_ENDDATE_FACT,float64,1716428,633653,36.92,2917,"[-153.0, -1710.0, -840.0, -825.0, -187.0]"
8,AMT_CREDIT_MAX_OVERDUE,float64,1716428,1124488,65.51,68251,"[77674.5, 0.0, 14985.0, 310.5, 20493.27]"
9,CNT_CREDIT_PROLONG,int64,1716428,0,0.00,10,"[0, 2, 1, 4, 3]"
10,AMT_CREDIT_SUM,float64,1716428,13,0.00,236708,"[91323.0, 225000.0, 464323.5, 90000.0, 2700000.0]"
11,AMT_CREDIT_SUM_DEBT,float64,1716428,257669,15.01,226537,"[0.0, 171342.0, 71017.38, 42103.8, 76905.0]"
12,AMT_CREDIT_SUM_LIMIT,float64,1716428,591780,34.48,51726,"[108982.62, 0.0, 228320.1, 411.615, 121690.17]"
13,AMT_CREDIT_SUM_OVERDUE,float64,1716428,0,0.00,1616,"[0.0, 231.525, 288.0, 58.5, 504.0]"
14,CREDIT_TYPE,object,1716428,0,0.00,15,"[Consumer credit, Credit card, Mortgage, Car l..."
15,DAYS_CREDIT_UPDATE,int64,1716428,0,0.00,2982,"[-131, -20, -16, -21, -31]"
16,AMT_ANNUITY,float64,1716428,1226791,71.47,40321,"[0.0, 2691.0, 24462.0, 8181.0, 8061.21]"

In [58]:
# Fitur 1: pernah nunggak atau tidak (flag)
b['FLAG_EVER_OVERDUE'] = b['AMT_CREDIT_MAX_OVERDUE'].notna().astype(int)

# Fitur 2: kalau pernah, berapa besarnya — sisanya isi 0
b['AMT_CREDIT_MAX_OVERDUE'] = b['AMT_CREDIT_MAX_OVERDUE'].fillna(0)

In [59]:
data_overview(b)

,Column,Data Type,Total Rows,Missing,% Missing,Unique Values,Unique Sample
0,SK_ID_CURR,int64,1716428,0,0.00,305811,"[215354, 162297, 402440, 238881, 222183]"
1,SK_ID_BUREAU,int64,1716428,0,0.00,1716428,"[5714462, 5714463, 5714464, 5714465, 5714466]"
2,CREDIT_ACTIVE,object,1716428,0,0.00,4,"[Closed, Active, Sold, Bad debt]"
3,CREDIT_CURRENCY,object,1716428,0,0.00,4,"[currency 1, currency 2, currency 4, currency 3]"
4,DAYS_CREDIT,int64,1716428,0,0.00,2923,"[-497, -208, -203, -629, -273]"
5,CREDIT_DAY_OVERDUE,int64,1716428,0,0.00,942,"[0, 2603, 6, 30, 2156]"
6,DAYS_CREDIT_ENDDATE,float64,1716428,105553,6.15,14096,"[-153.0, 1075.0, 528.0, 1197.0, 27460.0]"
7,DAYS_ENDDATE_FACT,float64,1716428,633653,36.92,2917,"[-153.0, -1710.0, -840.0, -825.0, -187.0]"
8,AMT_CREDIT_MAX_OVERDUE,float64,1716428,0,0.00,68251,"[0.0, 77674.5, 14985.0, 310.5, 20493.27]"
9,CNT_CREDIT_PROLONG,int64,1716428,0,0.00,10,"[0, 2, 1, 4, 3]"
10,AMT_CREDIT_SUM,float64,1716428,13,0.00,236708,"[91323.0, 225000.0, 464323.5, 90000.0, 2700000.0]"
11,AMT_CREDIT_SUM_DEBT,float64,1716428,257669,15.01,226537,"[0.0, 171342.0, 71017.38, 42103.8, 76905.0]"
12,AMT_CREDIT_SUM_LIMIT,float64,1716428,591780,34.48,51726,"[108982.62, 0.0, 228320.1, 411.615, 121690.17]"
13,AMT_CREDIT_SUM_OVERDUE,float64,1716428,0,0.00,1616,"[0.0, 231.525, 288.0, 58.5, 504.0]"
14,CREDIT_TYPE,object,1716428,0,0.00,15,"[Consumer credit, Credit card, Mortgage, Car l..."
15,DAYS_CREDIT_UPDATE,int64,1716428,0,0.00,2982,"[-131, -20, -16, -21, -31]"
16,AMT_ANNUITY,float64,1716428,1226791,71.47,40321,"[0.0, 2691.0, 24462.0, 8181.0, 8061.21]"
17,FLAG_EVER_OVERDUE,int64,1716428,0,0.00,2,"[0, 1]"

In [60]:
b['DAYS_CREDIT_ENDDATE'] = b['DAYS_CREDIT_ENDDATE'].fillna(b['DAYS_CREDIT_ENDDATE'].median())
b['AMT_CREDIT_SUM_DEBT'] = b['AMT_CREDIT_SUM_DEBT'].fillna(b['AMT_CREDIT_SUM_DEBT'].median())

In [61]:
data_overview(b)

,Column,Data Type,Total Rows,Missing,% Missing,Unique Values,Unique Sample
0,SK_ID_CURR,int64,1716428,0,0.00,305811,"[215354, 162297, 402440, 238881, 222183]"
1,SK_ID_BUREAU,int64,1716428,0,0.00,1716428,"[5714462, 5714463, 5714464, 5714465, 5714466]"
2,CREDIT_ACTIVE,object,1716428,0,0.00,4,"[Closed, Active, Sold, Bad debt]"
3,CREDIT_CURRENCY,object,1716428,0,0.00,4,"[currency 1, currency 2, currency 4, currency 3]"
4,DAYS_CREDIT,int64,1716428,0,0.00,2923,"[-497, -208, -203, -629, -273]"
5,CREDIT_DAY_OVERDUE,int64,1716428,0,0.00,942,"[0, 2603, 6, 30, 2156]"
6,DAYS_CREDIT_ENDDATE,float64,1716428,0,0.00,14096,"[-153.0, 1075.0, 528.0, -330.0, 1197.0]"
7,DAYS_ENDDATE_FACT,float64,1716428,633653,36.92,2917,"[-153.0, -1710.0, -840.0, -825.0, -187.0]"
8,AMT_CREDIT_MAX_OVERDUE,float64,1716428,0,0.00,68251,"[0.0, 77674.5, 14985.0, 310.5, 20493.27]"
9,CNT_CREDIT_PROLONG,int64,1716428,0,0.00,10,"[0, 2, 1, 4, 3]"
10,AMT_CREDIT_SUM,float64,1716428,13,0.00,236708,"[91323.0, 225000.0, 464323.5, 90000.0, 2700000.0]"
11,AMT_CREDIT_SUM_DEBT,float64,1716428,0,0.00,226537,"[0.0, 171342.0, 71017.38, 42103.8, 76905.0]"
12,AMT_CREDIT_SUM_LIMIT,float64,1716428,591780,34.48,51726,"[108982.62, 0.0, 228320.1, 411.615, 121690.17]"
13,AMT_CREDIT_SUM_OVERDUE,float64,1716428,0,0.00,1616,"[0.0, 231.525, 288.0, 58.5, 504.0]"
14,CREDIT_TYPE,object,1716428,0,0.00,15,"[Consumer credit, Credit card, Mortgage, Car l..."
15,DAYS_CREDIT_UPDATE,int64,1716428,0,0.00,2982,"[-131, -20, -16, -21, -31]"
16,AMT_ANNUITY,float64,1716428,1226791,71.47,40321,"[0.0, 2691.0, 24462.0, 8181.0, 8061.21]"
17,FLAG_EVER_OVERDUE,int64,1716428,0,0.00,2,"[0, 1]"

In [62]:
b['AMT_CREDIT_SUM_LIMIT'] = b['AMT_CREDIT_SUM_LIMIT'].fillna(b['AMT_CREDIT_SUM_LIMIT'].median())

In [63]:
b.drop(columns=['DAYS_ENDDATE_FACT'], inplace=True)

In [64]:
data_overview(b)

,Column,Data Type,Total Rows,Missing,% Missing,Unique Values,Unique Sample
0,SK_ID_CURR,int64,1716428,0,0.00,305811,"[215354, 162297, 402440, 238881, 222183]"
1,SK_ID_BUREAU,int64,1716428,0,0.00,1716428,"[5714462, 5714463, 5714464, 5714465, 5714466]"
2,CREDIT_ACTIVE,object,1716428,0,0.00,4,"[Closed, Active, Sold, Bad debt]"
3,CREDIT_CURRENCY,object,1716428,0,0.00,4,"[currency 1, currency 2, currency 4, currency 3]"
4,DAYS_CREDIT,int64,1716428,0,0.00,2923,"[-497, -208, -203, -629, -273]"
5,CREDIT_DAY_OVERDUE,int64,1716428,0,0.00,942,"[0, 2603, 6, 30, 2156]"
6,DAYS_CREDIT_ENDDATE,float64,1716428,0,0.00,14096,"[-153.0, 1075.0, 528.0, -330.0, 1197.0]"
7,AMT_CREDIT_MAX_OVERDUE,float64,1716428,0,0.00,68251,"[0.0, 77674.5, 14985.0, 310.5, 20493.27]"
8,CNT_CREDIT_PROLONG,int64,1716428,0,0.00,10,"[0, 2, 1, 4, 3]"
9,AMT_CREDIT_SUM,float64,1716428,13,0.00,236708,"[91323.0, 225000.0, 464323.5, 90000.0, 2700000.0]"
10,AMT_CREDIT_SUM_DEBT,float64,1716428,0,0.00,226537,"[0.0, 171342.0, 71017.38, 42103.8, 76905.0]"
11,AMT_CREDIT_SUM_LIMIT,float64,1716428,0,0.00,51726,"[0.0, 108982.62, 228320.1, 411.615, 121690.17]"
12,AMT_CREDIT_SUM_OVERDUE,float64,1716428,0,0.00,1616,"[0.0, 231.525, 288.0, 58.5, 504.0]"
13,CREDIT_TYPE,object,1716428,0,0.00,15,"[Consumer credit, Credit card, Mortgage, Car l..."
14,DAYS_CREDIT_UPDATE,int64,1716428,0,0.00,2982,"[-131, -20, -16, -21, -31]"
15,AMT_ANNUITY,float64,1716428,1226791,71.47,40321,"[0.0, 2691.0, 24462.0, 8181.0, 8061.21]"
16,FLAG_EVER_OVERDUE,int64,1716428,0,0.00,2,"[0, 1]"

In [65]:
b['AMT_CREDIT_SUM'] = b['AMT_CREDIT_SUM'].fillna(b['AMT_CREDIT_SUM'].median())

In [66]:
data_overview(b)

,Column,Data Type,Total Rows,Missing,% Missing,Unique Values,Unique Sample
0,SK_ID_CURR,int64,1716428,0,0.00,305811,"[215354, 162297, 402440, 238881, 222183]"
1,SK_ID_BUREAU,int64,1716428,0,0.00,1716428,"[5714462, 5714463, 5714464, 5714465, 5714466]"
2,CREDIT_ACTIVE,object,1716428,0,0.00,4,"[Closed, Active, Sold, Bad debt]"
3,CREDIT_CURRENCY,object,1716428,0,0.00,4,"[currency 1, currency 2, currency 4, currency 3]"
4,DAYS_CREDIT,int64,1716428,0,0.00,2923,"[-497, -208, -203, -629, -273]"
5,CREDIT_DAY_OVERDUE,int64,1716428,0,0.00,942,"[0, 2603, 6, 30, 2156]"
6,DAYS_CREDIT_ENDDATE,float64,1716428,0,0.00,14096,"[-153.0, 1075.0, 528.0, -330.0, 1197.0]"
7,AMT_CREDIT_MAX_OVERDUE,float64,1716428,0,0.00,68251,"[0.0, 77674.5, 14985.0, 310.5, 20493.27]"
8,CNT_CREDIT_PROLONG,int64,1716428,0,0.00,10,"[0, 2, 1, 4, 3]"
9,AMT_CREDIT_SUM,float64,1716428,0,0.00,236708,"[91323.0, 225000.0, 464323.5, 90000.0, 2700000.0]"
10,AMT_CREDIT_SUM_DEBT,float64,1716428,0,0.00,226537,"[0.0, 171342.0, 71017.38, 42103.8, 76905.0]"
11,AMT_CREDIT_SUM_LIMIT,float64,1716428,0,0.00,51726,"[0.0, 108982.62, 228320.1, 411.615, 121690.17]"
12,AMT_CREDIT_SUM_OVERDUE,float64,1716428,0,0.00,1616,"[0.0, 231.525, 288.0, 58.5, 504.0]"
13,CREDIT_TYPE,object,1716428,0,0.00,15,"[Consumer credit, Credit card, Mortgage, Car l..."
14,DAYS_CREDIT_UPDATE,int64,1716428,0,0.00,2982,"[-131, -20, -16, -21, -31]"
15,AMT_ANNUITY,float64,1716428,1226791,71.47,40321,"[0.0, 2691.0, 24462.0, 8181.0, 8061.21]"
16,FLAG_EVER_OVERDUE,int64,1716428,0,0.00,2,"[0, 1]"

## Data Cleaning - Bureau Balance ( NO MISSING VALUE )

In [67]:
data_overview(bb)

,Column,Data Type,Total Rows,Missing,% Missing,Unique Values,Unique Sample
0,SK_ID_BUREAU,int64,27299925,0,0.00,817395,"[5715448, 5715449, 5715451, 5715452, 5715453]"
1,MONTHS_BALANCE,int64,27299925,0,0.00,97,"[0, -1, -2, -3, -4]"
2,STATUS,object,27299925,0,0.00,8,"[C, 0, X, 1, 2]"

## Data Cleaning - Credit Card Balance

In [68]:
data_overview(ccb)

,Column,Data Type,Total Rows,Missing,% Missing,Unique Values,Unique Sample
0,SK_ID_PREV,int64,3840312,0,0.00,104307,"[2562384, 2582071, 1740877, 1389973, 1891521]"
1,SK_ID_CURR,int64,3840312,0,0.00,103558,"[378907, 363914, 371185, 337855, 126868]"
2,MONTHS_BALANCE,int64,3840312,0,0.00,96,"[-6, -1, -7, -4, -5]"
3,AMT_BALANCE,float64,3840312,0,0.00,1347904,"[56.97, 63975.555, 31815.225, 236572.11, 45391..."
4,AMT_CREDIT_LIMIT_ACTUAL,int64,3840312,0,0.00,181,"[135000, 45000, 450000, 225000, 270000]"
5,AMT_DRAWINGS_ATM_CURRENT,float64,3840312,749816,19.52,2267,"[0.0, 2250.0, 67500.0, 45000.0, 90000.0]"
6,AMT_DRAWINGS_CURRENT,float64,3840312,0,0.00,187005,"[877.5, 2250.0, 0.0, 11547.0, 67500.0]"
7,AMT_DRAWINGS_OTHER_CURRENT,float64,3840312,749816,19.52,1832,"[0.0, 137700.0, 177840.0, 46800.0, 187200.0]"
8,AMT_DRAWINGS_POS_CURRENT,float64,3840312,749816,19.52,168748,"[877.5, 0.0, 11547.0, 199339.425, 34526.7]"
9,AMT_INST_MIN_REGULARITY,float64,3840312,305236,7.95,312266,"[1700.325, 2250.0, 11795.76, 22924.89, 4449.105]"
10,AMT_PAYMENT_CURRENT,float64,3840312,767988,20.00,163209,"[1800.0, 2250.0, 11925.0, 27000.0, 3825.0]"
11,AMT_PAYMENT_TOTAL_CURRENT,float64,3840312,0,0.00,182957,"[1800.0, 2250.0, 11925.0, 27000.0, 3825.0]"
12,AMT_RECEIVABLE_PRINCIPAL,float64,3840312,0,0.00,1195839,"[0.0, 60175.08, 26926.425, 224949.285, 443044...."
13,AMT_RECIVABLE,float64,3840312,0,0.00,1338878,"[0.0, 64875.555, 31460.085, 233048.97, 453919...."
14,AMT_TOTAL_RECEIVABLE,float64,3840312,0,0.00,1339008,"[0.0, 64875.555, 31460.085, 233048.97, 453919...."
15,CNT_DRAWINGS_ATM_CURRENT,float64,3840312,749816,19.52,44,"[0.0, 1.0, 3.0, 5.0, 2.0]"
16,CNT_DRAWINGS_CURRENT,int64,3840312,0,0.00,129,"[1, 0, 8, 9, 5]"
17,CNT_DRAWINGS_OTHER_CURRENT,float64,3840312,749816,19.52,11,"[0.0, 1.0, 3.0, 2.0, 4.0]"
18,CNT_DRAWINGS_POS_CURRENT,float64,3840312,749816,19.52,133,"[1.0, 0.0, 5.0, 6.0, 29.0]"
19,CNT_INSTALMENT_MATURE_CUM,float64,3840312,305236,7.95,121,"[35.0, 69.0, 30.0, 10.0, 101.0]"
20,NAME_CONTRACT_STATUS,object,3840312,0,0.00,7,"[Active, Completed, Demand, Signed, Sent propo..."
21,SK_DPD,int64,3840312,0,0.00,917,"[0, 7, 2192, 717, 28]"
22,SK_DPD_DEF,int64,3840312,0,0.00,378,"[0, 7, 99, 1, 701]"

In [69]:
cols_zero = [
    'AMT_DRAWINGS_ATM_CURRENT',
    'AMT_DRAWINGS_OTHER_CURRENT',
    'AMT_DRAWINGS_POS_CURRENT',
    'CNT_DRAWINGS_ATM_CURRENT',
    'CNT_DRAWINGS_OTHER_CURRENT',
    'CNT_DRAWINGS_POS_CURRENT'
]

for col in cols_zero:
    ccb[f'{col}_missing'] = ccb[col].isna().astype(int)
    ccb[col] = ccb[col].fillna(0)

In [70]:
data_overview(ccb)

,Column,Data Type,Total Rows,Missing,% Missing,Unique Values,Unique Sample
0,SK_ID_PREV,int64,3840312,0,0.00,104307,"[2562384, 2582071, 1740877, 1389973, 1891521]"
1,SK_ID_CURR,int64,3840312,0,0.00,103558,"[378907, 363914, 371185, 337855, 126868]"
2,MONTHS_BALANCE,int64,3840312,0,0.00,96,"[-6, -1, -7, -4, -5]"
3,AMT_BALANCE,float64,3840312,0,0.00,1347904,"[56.97, 63975.555, 31815.225, 236572.11, 45391..."
4,AMT_CREDIT_LIMIT_ACTUAL,int64,3840312,0,0.00,181,"[135000, 45000, 450000, 225000, 270000]"
5,AMT_DRAWINGS_ATM_CURRENT,float64,3840312,0,0.00,2267,"[0.0, 2250.0, 67500.0, 45000.0, 90000.0]"
6,AMT_DRAWINGS_CURRENT,float64,3840312,0,0.00,187005,"[877.5, 2250.0, 0.0, 11547.0, 67500.0]"
7,AMT_DRAWINGS_OTHER_CURRENT,float64,3840312,0,0.00,1832,"[0.0, 137700.0, 177840.0, 46800.0, 187200.0]"
8,AMT_DRAWINGS_POS_CURRENT,float64,3840312,0,0.00,168748,"[877.5, 0.0, 11547.0, 199339.425, 34526.7]"
9,AMT_INST_MIN_REGULARITY,float64,3840312,305236,7.95,312266,"[1700.325, 2250.0, 11795.76, 22924.89, 4449.105]"
10,AMT_PAYMENT_CURRENT,float64,3840312,767988,20.00,163209,"[1800.0, 2250.0, 11925.0, 27000.0, 3825.0]"
11,AMT_PAYMENT_TOTAL_CURRENT,float64,3840312,0,0.00,182957,"[1800.0, 2250.0, 11925.0, 27000.0, 3825.0]"
12,AMT_RECEIVABLE_PRINCIPAL,float64,3840312,0,0.00,1195839,"[0.0, 60175.08, 26926.425, 224949.285, 443044...."
13,AMT_RECIVABLE,float64,3840312,0,0.00,1338878,"[0.0, 64875.555, 31460.085, 233048.97, 453919...."
14,AMT_TOTAL_RECEIVABLE,float64,3840312,0,0.00,1339008,"[0.0, 64875.555, 31460.085, 233048.97, 453919...."
15,CNT_DRAWINGS_ATM_CURRENT,float64,3840312,0,0.00,44,"[0.0, 1.0, 3.0, 5.0, 2.0]"
16,CNT_DRAWINGS_CURRENT,int64,3840312,0,0.00,129,"[1, 0, 8, 9, 5]"
17,CNT_DRAWINGS_OTHER_CURRENT,float64,3840312,0,0.00,11,"[0.0, 1.0, 3.0, 2.0, 4.0]"
18,CNT_DRAWINGS_POS_CURRENT,float64,3840312,0,0.00,133,"[1.0, 0.0, 5.0, 6.0, 29.0]"
19,CNT_INSTALMENT_MATURE_CUM,float64,3840312,305236,7.95,121,"[35.0, 69.0, 30.0, 10.0, 101.0]"
20,NAME_CONTRACT_STATUS,object,3840312,0,0.00,7,"[Active, Completed, Demand, Signed, Sent propo..."
21,SK_DPD,int64,3840312,0,0.00,917,"[0, 7, 2192, 717, 28]"
22,SK_DPD_DEF,int64,3840312,0,0.00,378,"[0, 7, 99, 1, 701]"
23,AMT_DRAWINGS_ATM_CURRENT_missing,int64,3840312,0,0.00,2,"[0, 1]"
24,AMT_DRAWINGS_OTHER_CURRENT_missing,int64,3840312,0,0.00,2,"[0, 1]"
25,AMT_DRAWINGS_POS_CURRENT_missing,int64,3840312,0,0.00,2,"[0, 1]"
26,CNT_DRAWINGS_ATM_CURRENT_missing,int64,3840312,0,0.00,2,"[0, 1]"
27,CNT_DRAWINGS_OTHER_CURRENT_missing,int64,3840312,0,0.00,2,"[0, 1]"
28,CNT_DRAWINGS_POS_CURRENT_missing,int64,3840312,0,0.00,2,"[0, 1]"

In [71]:
ccb['AMT_INST_MIN_REGULARITY'] = ccb['AMT_INST_MIN_REGULARITY'].fillna(ccb['AMT_INST_MIN_REGULARITY'].median())
ccb['CNT_INSTALMENT_MATURE_CUM'] = ccb['CNT_INSTALMENT_MATURE_CUM'].fillna(ccb['CNT_INSTALMENT_MATURE_CUM'].mode()[0])

In [72]:
data_overview(ccb)

,Column,Data Type,Total Rows,Missing,% Missing,Unique Values,Unique Sample
0,SK_ID_PREV,int64,3840312,0,0.00,104307,"[2562384, 2582071, 1740877, 1389973, 1891521]"
1,SK_ID_CURR,int64,3840312,0,0.00,103558,"[378907, 363914, 371185, 337855, 126868]"
2,MONTHS_BALANCE,int64,3840312,0,0.00,96,"[-6, -1, -7, -4, -5]"
3,AMT_BALANCE,float64,3840312,0,0.00,1347904,"[56.97, 63975.555, 31815.225, 236572.11, 45391..."
4,AMT_CREDIT_LIMIT_ACTUAL,int64,3840312,0,0.00,181,"[135000, 45000, 450000, 225000, 270000]"
5,AMT_DRAWINGS_ATM_CURRENT,float64,3840312,0,0.00,2267,"[0.0, 2250.0, 67500.0, 45000.0, 90000.0]"
6,AMT_DRAWINGS_CURRENT,float64,3840312,0,0.00,187005,"[877.5, 2250.0, 0.0, 11547.0, 67500.0]"
7,AMT_DRAWINGS_OTHER_CURRENT,float64,3840312,0,0.00,1832,"[0.0, 137700.0, 177840.0, 46800.0, 187200.0]"
8,AMT_DRAWINGS_POS_CURRENT,float64,3840312,0,0.00,168748,"[877.5, 0.0, 11547.0, 199339.425, 34526.7]"
9,AMT_INST_MIN_REGULARITY,float64,3840312,0,0.00,312266,"[1700.325, 2250.0, 11795.76, 22924.89, 4449.105]"
10,AMT_PAYMENT_CURRENT,float64,3840312,767988,20.00,163209,"[1800.0, 2250.0, 11925.0, 27000.0, 3825.0]"
11,AMT_PAYMENT_TOTAL_CURRENT,float64,3840312,0,0.00,182957,"[1800.0, 2250.0, 11925.0, 27000.0, 3825.0]"
12,AMT_RECEIVABLE_PRINCIPAL,float64,3840312,0,0.00,1195839,"[0.0, 60175.08, 26926.425, 224949.285, 443044...."
13,AMT_RECIVABLE,float64,3840312,0,0.00,1338878,"[0.0, 64875.555, 31460.085, 233048.97, 453919...."
14,AMT_TOTAL_RECEIVABLE,float64,3840312,0,0.00,1339008,"[0.0, 64875.555, 31460.085, 233048.97, 453919...."
15,CNT_DRAWINGS_ATM_CURRENT,float64,3840312,0,0.00,44,"[0.0, 1.0, 3.0, 5.0, 2.0]"
16,CNT_DRAWINGS_CURRENT,int64,3840312,0,0.00,129,"[1, 0, 8, 9, 5]"
17,CNT_DRAWINGS_OTHER_CURRENT,float64,3840312,0,0.00,11,"[0.0, 1.0, 3.0, 2.0, 4.0]"
18,CNT_DRAWINGS_POS_CURRENT,float64,3840312,0,0.00,133,"[1.0, 0.0, 5.0, 6.0, 29.0]"
19,CNT_INSTALMENT_MATURE_CUM,float64,3840312,0,0.00,121,"[35.0, 69.0, 30.0, 10.0, 101.0]"
20,NAME_CONTRACT_STATUS,object,3840312,0,0.00,7,"[Active, Completed, Demand, Signed, Sent propo..."
21,SK_DPD,int64,3840312,0,0.00,917,"[0, 7, 2192, 717, 28]"
22,SK_DPD_DEF,int64,3840312,0,0.00,378,"[0, 7, 99, 1, 701]"
23,AMT_DRAWINGS_ATM_CURRENT_missing,int64,3840312,0,0.00,2,"[0, 1]"
24,AMT_DRAWINGS_OTHER_CURRENT_missing,int64,3840312,0,0.00,2,"[0, 1]"
25,AMT_DRAWINGS_POS_CURRENT_missing,int64,3840312,0,0.00,2,"[0, 1]"
26,CNT_DRAWINGS_ATM_CURRENT_missing,int64,3840312,0,0.00,2,"[0, 1]"
27,CNT_DRAWINGS_OTHER_CURRENT_missing,int64,3840312,0,0.00,2,"[0, 1]"
28,CNT_DRAWINGS_POS_CURRENT_missing,int64,3840312,0,0.00,2,"[0, 1]"

In [73]:
print("Mean  :", ccb['AMT_PAYMENT_CURRENT'].mean())
print("Median:", ccb['AMT_PAYMENT_CURRENT'].median())
print("Mode  :", ccb['AMT_PAYMENT_CURRENT'].mode()[0])

Mean  : 10280.53770200018
Median: 2702.7
Mode  : 0.0

In [74]:
ccb['AMT_PAYMENT_CURRENT'] = ccb['AMT_PAYMENT_CURRENT'].fillna(ccb['AMT_PAYMENT_CURRENT'].median())

In [75]:
data_overview(ccb)

,Column,Data Type,Total Rows,Missing,% Missing,Unique Values,Unique Sample
0,SK_ID_PREV,int64,3840312,0,0.00,104307,"[2562384, 2582071, 1740877, 1389973, 1891521]"
1,SK_ID_CURR,int64,3840312,0,0.00,103558,"[378907, 363914, 371185, 337855, 126868]"
2,MONTHS_BALANCE,int64,3840312,0,0.00,96,"[-6, -1, -7, -4, -5]"
3,AMT_BALANCE,float64,3840312,0,0.00,1347904,"[56.97, 63975.555, 31815.225, 236572.11, 45391..."
4,AMT_CREDIT_LIMIT_ACTUAL,int64,3840312,0,0.00,181,"[135000, 45000, 450000, 225000, 270000]"
5,AMT_DRAWINGS_ATM_CURRENT,float64,3840312,0,0.00,2267,"[0.0, 2250.0, 67500.0, 45000.0, 90000.0]"
6,AMT_DRAWINGS_CURRENT,float64,3840312,0,0.00,187005,"[877.5, 2250.0, 0.0, 11547.0, 67500.0]"
7,AMT_DRAWINGS_OTHER_CURRENT,float64,3840312,0,0.00,1832,"[0.0, 137700.0, 177840.0, 46800.0, 187200.0]"
8,AMT_DRAWINGS_POS_CURRENT,float64,3840312,0,0.00,168748,"[877.5, 0.0, 11547.0, 199339.425, 34526.7]"
9,AMT_INST_MIN_REGULARITY,float64,3840312,0,0.00,312266,"[1700.325, 2250.0, 11795.76, 22924.89, 4449.105]"
10,AMT_PAYMENT_CURRENT,float64,3840312,0,0.00,163209,"[1800.0, 2250.0, 11925.0, 27000.0, 3825.0]"
11,AMT_PAYMENT_TOTAL_CURRENT,float64,3840312,0,0.00,182957,"[1800.0, 2250.0, 11925.0, 27000.0, 3825.0]"
12,AMT_RECEIVABLE_PRINCIPAL,float64,3840312,0,0.00,1195839,"[0.0, 60175.08, 26926.425, 224949.285, 443044...."
13,AMT_RECIVABLE,float64,3840312,0,0.00,1338878,"[0.0, 64875.555, 31460.085, 233048.97, 453919...."
14,AMT_TOTAL_RECEIVABLE,float64,3840312,0,0.00,1339008,"[0.0, 64875.555, 31460.085, 233048.97, 453919...."
15,CNT_DRAWINGS_ATM_CURRENT,float64,3840312,0,0.00,44,"[0.0, 1.0, 3.0, 5.0, 2.0]"
16,CNT_DRAWINGS_CURRENT,int64,3840312,0,0.00,129,"[1, 0, 8, 9, 5]"
17,CNT_DRAWINGS_OTHER_CURRENT,float64,3840312,0,0.00,11,"[0.0, 1.0, 3.0, 2.0, 4.0]"
18,CNT_DRAWINGS_POS_CURRENT,float64,3840312,0,0.00,133,"[1.0, 0.0, 5.0, 6.0, 29.0]"
19,CNT_INSTALMENT_MATURE_CUM,float64,3840312,0,0.00,121,"[35.0, 69.0, 30.0, 10.0, 101.0]"
20,NAME_CONTRACT_STATUS,object,3840312,0,0.00,7,"[Active, Completed, Demand, Signed, Sent propo..."
21,SK_DPD,int64,3840312,0,0.00,917,"[0, 7, 2192, 717, 28]"
22,SK_DPD_DEF,int64,3840312,0,0.00,378,"[0, 7, 99, 1, 701]"
23,AMT_DRAWINGS_ATM_CURRENT_missing,int64,3840312,0,0.00,2,"[0, 1]"
24,AMT_DRAWINGS_OTHER_CURRENT_missing,int64,3840312,0,0.00,2,"[0, 1]"
25,AMT_DRAWINGS_POS_CURRENT_missing,int64,3840312,0,0.00,2,"[0, 1]"
26,CNT_DRAWINGS_ATM_CURRENT_missing,int64,3840312,0,0.00,2,"[0, 1]"
27,CNT_DRAWINGS_OTHER_CURRENT_missing,int64,3840312,0,0.00,2,"[0, 1]"
28,CNT_DRAWINGS_POS_CURRENT_missing,int64,3840312,0,0.00,2,"[0, 1]"

## Cleaning Installments_payments dataset

In [76]:
data_overview(ip)

,Column,Data Type,Total Rows,Missing,% Missing,Unique Values,Unique Sample
0,SK_ID_PREV,int64,13605401,0,0.00,997752,"[1054186, 1330831, 2085231, 2452527, 2714724]"
1,SK_ID_CURR,int64,13605401,0,0.00,339587,"[161674, 151639, 193053, 199697, 167756]"
2,NUM_INSTALMENT_VERSION,float64,13605401,0,0.00,65,"[1.0, 0.0, 2.0, 4.0, 3.0]"
3,NUM_INSTALMENT_NUMBER,int64,13605401,0,0.00,277,"[6, 34, 1, 3, 2]"
4,DAYS_INSTALMENT,float64,13605401,0,0.00,2922,"[-1180.0, -2156.0, -63.0, -2418.0, -1383.0]"
5,DAYS_ENTRY_PAYMENT,float64,13605401,2905,0.02,3039,"[-1187.0, -2156.0, -63.0, -2426.0, -1366.0]"
6,AMT_INSTALMENT,float64,13605401,0,0.00,902539,"[6948.36, 1716.525, 25425.0, 24350.13, 2165.04]"
7,AMT_PAYMENT,float64,13605401,2905,0.02,944235,"[6948.36, 1716.525, 25425.0, 24350.13, 2160.585]"

In [77]:
ip.head()

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
0,1054186,161674,1.00,6,-1180.00,-1187.00,6948.36,6948.36
1,1330831,151639,0.00,34,-2156.00,-2156.00,1716.53,1716.53
2,2085231,193053,2.00,1,-63.00,-63.00,25425.00,25425.00
3,2452527,199697,1.00,3,-2418.00,-2426.00,24350.13,24350.13
4,2714724,167756,1.00,2,-1383.00,-1366.00,2165.04,2160.59

In [78]:
ip.describe()

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
count,13605401.00,13605401.00,13605401.00,13605401.00,13605401.00,13602496.00,13605401.00,13602496.00
mean,1903364.97,278444.88,0.86,18.87,-1042.27,-1051.11,17050.91,17238.22
std,536202.91,102718.31,1.04,26.66,800.95,800.59,50570.25,54735.78
min,1000001.00,100001.00,0.00,1.00,-2922.00,-4921.00,0.00,0.00
25%,1434191.00,189639.00,0.00,4.00,-1654.00,-1662.00,4226.09,3398.26
50%,1896520.00,278685.00,1.00,8.00,-818.00,-827.00,8884.08,8125.52
75%,2369094.00,367530.00,1.00,19.00,-361.00,-370.00,16710.21,16108.42
max,2843499.00,456255.00,178.00,277.00,-1.00,-1.00,3771487.85,3771487.85

In [79]:
ip['DAYS_ENTRY_PAYMENT'] = ip['DAYS_ENTRY_PAYMENT'].fillna(ip['DAYS_ENTRY_PAYMENT'].median())
ip['AMT_PAYMENT'] = ip['AMT_PAYMENT'].fillna(ip['AMT_PAYMENT'].median())

In [80]:
data_overview(ip)

,Column,Data Type,Total Rows,Missing,% Missing,Unique Values,Unique Sample
0,SK_ID_PREV,int64,13605401,0,0.00,997752,"[1054186, 1330831, 2085231, 2452527, 2714724]"
1,SK_ID_CURR,int64,13605401,0,0.00,339587,"[161674, 151639, 193053, 199697, 167756]"
2,NUM_INSTALMENT_VERSION,float64,13605401,0,0.00,65,"[1.0, 0.0, 2.0, 4.0, 3.0]"
3,NUM_INSTALMENT_NUMBER,int64,13605401,0,0.00,277,"[6, 34, 1, 3, 2]"
4,DAYS_INSTALMENT,float64,13605401,0,0.00,2922,"[-1180.0, -2156.0, -63.0, -2418.0, -1383.0]"
5,DAYS_ENTRY_PAYMENT,float64,13605401,0,0.00,3039,"[-1187.0, -2156.0, -63.0, -2426.0, -1366.0]"
6,AMT_INSTALMENT,float64,13605401,0,0.00,902539,"[6948.36, 1716.525, 25425.0, 24350.13, 2165.04]"
7,AMT_PAYMENT,float64,13605401,0,0.00,944235,"[6948.36, 1716.525, 25425.0, 24350.13, 2160.585]"

## Cleaning PCB

In [81]:
data_overview(pcb)

,Column,Data Type,Total Rows,Missing,% Missing,Unique Values,Unique Sample
0,SK_ID_PREV,int64,10001358,0,0.00,936325,"[1803195, 1715348, 1784872, 1903291, 2341044]"
1,SK_ID_CURR,int64,10001358,0,0.00,337252,"[182943, 367990, 397406, 269225, 334279]"
2,MONTHS_BALANCE,int64,10001358,0,0.00,96,"[-31, -33, -32, -35, -38]"
3,CNT_INSTALMENT,float64,10001358,26071,0.26,73,"[48.0, 36.0, 12.0, 24.0, 60.0]"
4,CNT_INSTALMENT_FUTURE,float64,10001358,26087,0.26,79,"[45.0, 35.0, 9.0, 42.0, 12.0]"
5,NAME_CONTRACT_STATUS,object,10001358,0,0.00,9,"[Active, Completed, Signed, Approved, Returned..."
6,SK_DPD,int64,10001358,0,0.00,3400,"[0, 1, 2, 4, 3]"
7,SK_DPD_DEF,int64,10001358,0,0.00,2307,"[0, 1, 2, 4, 3]"

In [82]:
pcb.head()

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,1803195,182943,-31,48.00,45.00,Active,0,0
1,1715348,367990,-33,36.00,35.00,Active,0,0
2,1784872,397406,-32,12.00,9.00,Active,0,0
3,1903291,269225,-35,48.00,42.00,Active,0,0
4,2341044,334279,-35,36.00,35.00,Active,0,0

In [83]:
pcb['CNT_INSTALMENT'] = pcb['CNT_INSTALMENT'].fillna(pcb['CNT_INSTALMENT'].median())
pcb['CNT_INSTALMENT_FUTURE'] = pcb['CNT_INSTALMENT_FUTURE'].fillna(pcb['CNT_INSTALMENT_FUTURE'].median())

In [84]:
data_overview(pcb)

,Column,Data Type,Total Rows,Missing,% Missing,Unique Values,Unique Sample
0,SK_ID_PREV,int64,10001358,0,0.00,936325,"[1803195, 1715348, 1784872, 1903291, 2341044]"
1,SK_ID_CURR,int64,10001358,0,0.00,337252,"[182943, 367990, 397406, 269225, 334279]"
2,MONTHS_BALANCE,int64,10001358,0,0.00,96,"[-31, -33, -32, -35, -38]"
3,CNT_INSTALMENT,float64,10001358,0,0.00,73,"[48.0, 36.0, 12.0, 24.0, 60.0]"
4,CNT_INSTALMENT_FUTURE,float64,10001358,0,0.00,79,"[45.0, 35.0, 9.0, 42.0, 12.0]"
5,NAME_CONTRACT_STATUS,object,10001358,0,0.00,9,"[Active, Completed, Signed, Approved, Returned..."
6,SK_DPD,int64,10001358,0,0.00,3400,"[0, 1, 2, 4, 3]"
7,SK_DPD_DEF,int64,10001358,0,0.00,2307,"[0, 1, 2, 4, 3]"

## Data Cleaning - previous_application dataset

In [85]:
data_overview(pa)

,Column,Data Type,Total Rows,Missing,% Missing,Unique Values,Unique Sample
0,SK_ID_PREV,int64,1670214,0,0.00,1670214,"[2030495, 2802425, 2523466, 2819243, 1784265]"
1,SK_ID_CURR,int64,1670214,0,0.00,338857,"[271877, 108129, 122040, 176158, 202054]"
2,NAME_CONTRACT_TYPE,object,1670214,0,0.00,4,"[Consumer loans, Cash loans, Revolving loans, ..."
3,AMT_ANNUITY,float64,1670214,372235,22.29,357959,"[1730.43, 25188.615, 15060.735, 47041.335, 319..."
4,AMT_APPLICATION,float64,1670214,0,0.00,93885,"[17145.0, 607500.0, 112500.0, 450000.0, 337500.0]"
5,AMT_CREDIT,float64,1670214,1,0.00,86803,"[17145.0, 679671.0, 136444.5, 470790.0, 404055.0]"
6,AMT_DOWN_PAYMENT,float64,1670214,895844,53.64,29278,"[0.0, 12649.5, 1350.0, 9000.0, 13500.0]"
7,AMT_GOODS_PRICE,float64,1670214,385515,23.08,93885,"[17145.0, 607500.0, 112500.0, 450000.0, 337500.0]"
8,WEEKDAY_APPR_PROCESS_START,object,1670214,0,0.00,7,"[SATURDAY, THURSDAY, TUESDAY, MONDAY, FRIDAY]"
9,HOUR_APPR_PROCESS_START,int64,1670214,0,0.00,24,"[15, 11, 7, 9, 8]"
10,FLAG_LAST_APPL_PER_CONTRACT,object,1670214,0,0.00,2,"[Y, N]"
11,NFLAG_LAST_APPL_IN_DAY,int64,1670214,0,0.00,2,"[1, 0]"
12,RATE_DOWN_PAYMENT,float64,1670214,895844,53.64,207033,"[0.0, 0.1039712869911545, 0.0513237940193642, ..."
13,RATE_INTEREST_PRIMARY,float64,1670214,1664263,99.64,148,"[0.1828318032415278, 0.1969143148588915, 0.189..."
14,RATE_INTEREST_PRIVILEGED,float64,1670214,1664263,99.64,25,"[0.8673361522198731, 0.8350951374207188, 0.568..."
15,NAME_CASH_LOAN_PURPOSE,object,1670214,0,0.00,25,"[XAP, XNA, Repairs, Everyday expenses, Car rep..."
16,NAME_CONTRACT_STATUS,object,1670214,0,0.00,4,"[Approved, Refused, Canceled, Unused offer]"
17,DAYS_DECISION,int64,1670214,0,0.00,2922,"[-73, -164, -301, -512, -781]"
18,NAME_PAYMENT_TYPE,object,1670214,0,0.00,4,"[Cash through the bank, XNA, Non-cash from you..."
19,CODE_REJECT_REASON,object,1670214,0,0.00,9,"[XAP, HC, LIMIT, CLIENT, SCOFR]"
20,NAME_TYPE_SUITE,object,1670214,820405,49.12,7,"[Unaccompanied, Spouse, partner, Family, Child..."
21,NAME_CLIENT_TYPE,object,1670214,0,0.00,4,"[Repeater, New, Refreshed, XNA]"
22,NAME_GOODS_CATEGORY,object,1670214,0,0.00,28,"[Mobile, XNA, Consumer Electronics, Constructi..."
23,NAME_PORTFOLIO,object,1670214,0,0.00,5,"[POS, Cash, XNA, Cards, Cars]"
24,NAME_PRODUCT_TYPE,object,1670214,0,0.00,3,"[XNA, x-sell, walk-in]"
25,CHANNEL_TYPE,object,1670214,0,0.00,8,"[Country-wide, Contact center, Credit and cash..."
26,SELLERPLACE_AREA,int64,1670214,0,0.00,2097,"[35, -1, 200, 83, 130]"
27,NAME_SELLER_INDUSTRY,object,1670214,0,0.00,11,"[Connectivity, XNA, Consumer electronics, Indu..."
28,CNT_PAYMENT,float64,1670214,372230,22.29,49,"[12.0, 36.0, 24.0, 18.0, 54.0]"
29,NAME_YIELD_GROUP,object,1670214,0,0.00,5,"[middle, low_action, high, low_normal, XNA]"
30,PRODUCT_COMBINATION,object,1670214,346,0.02,17,"[POS mobile with interest, Cash X-Sell: low, C..."
31,DAYS_FIRST_DRAWING,float64,1670214,673065,40.30,2838,"[365243.0, -277.0, -265.0, -479.0, -332.0]"
32,DAYS_FIRST_DUE,float64,1670214,673065,40.30,2892,"[-42.0, -134.0, -271.0, -482.0, -654.0]"
33,DAYS_LAST_DUE_1ST_VERSION,float64,1670214,673065,40.30,4605,"[300.0, 916.0, 59.0, -152.0, -144.0]"
34,DAYS_LAST_DUE,float64,1670214,673065,40.30,2873,"[-42.0, 365243.0, -182.0, -144.0, -345.0]"
35,DAYS_TERMINATION,float64,1670214,673065,40.30,2830,"[-37.0, 365243.0, -177.0, -137.0, -334.0]"
36,NFLAG_INSURED_ON_APPROVAL,float64,1670214,673065,40.30,2,"[0.0, 1.0]"

In [86]:
pa.drop(columns=['RATE_INTEREST_PRIMARY', 'RATE_INTEREST_PRIVILEGED', 'AMT_DOWN_PAYMENT', 'RATE_DOWN_PAYMENT'], inplace=True)

In [87]:
pa['NAME_TYPE_SUITE'] = pa['NAME_TYPE_SUITE'].fillna('Unknown')

In [88]:
pa.describe()

,SK_ID_PREV,SK_ID_CURR,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_GOODS_PRICE,HOUR_APPR_PROCESS_START,NFLAG_LAST_APPL_IN_DAY,DAYS_DECISION,SELLERPLACE_AREA,CNT_PAYMENT,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
count,1670214.00,1670214.00,1297979.00,1670214.00,1670213.00,1284699.00,1670214.00,1670214.00,1670214.00,1670214.00,1297984.00,997149.00,997149.00,997149.00,997149.00,997149.00,997149.00
mean,1923089.14,278357.17,15955.12,175233.86,196114.02,227847.28,12.48,1.00,-880.68,313.95,16.05,342209.86,13826.27,33767.77,76582.40,81992.34,0.33
std,532597.96,102814.82,14782.14,292779.76,318574.62,315396.56,3.33,0.06,779.10,7127.44,14.57,88916.12,72444.87,106857.03,149647.42,153303.52,0.47
min,1000001.00,100001.00,0.00,0.00,0.00,0.00,0.00,0.00,-2922.00,-1.00,0.00,-2922.00,-2892.00,-2801.00,-2889.00,-2874.00,0.00
25%,1461857.25,189329.00,6321.78,18720.00,24160.50,50841.00,10.00,1.00,-1300.00,-1.00,6.00,365243.00,-1628.00,-1242.00,-1314.00,-1270.00,0.00
50%,1923110.50,278714.50,11250.00,71046.00,80541.00,112320.00,12.00,1.00,-581.00,3.00,12.00,365243.00,-831.00,-361.00,-537.00,-499.00,0.00
75%,2384279.75,367514.00,20658.42,180360.00,216418.50,234000.00,15.00,1.00,-280.00,82.00,24.00,365243.00,-411.00,129.00,-74.00,-44.00,1.00
max,2845382.00,456255.00,418058.15,6905160.00,6905160.00,6905160.00,23.00,1.00,-1.00,4000000.00,84.00,365243.00,365243.00,365243.00,365243.00,365243.00,1.00

In [89]:
pa['AMT_ANNUITY'] = pa['AMT_ANNUITY'].fillna(pa['AMT_ANNUITY'].median())
pa['AMT_GOODS_PRICE'] = pa['AMT_GOODS_PRICE'].fillna(pa['AMT_GOODS_PRICE'].median())
pa['CNT_PAYMENT'] = pa['CNT_PAYMENT'].fillna(pa['CNT_PAYMENT'].mode()[0])

In [90]:
print("Mean  :", pa['CNT_PAYMENT'].mean())
print("Median:", pa['CNT_PAYMENT'].median())
print("Mode  :", pa['CNT_PAYMENT'].mode()[0])

Mean  : 15.150574118047148
Median: 12.0
Mode  : 12.0

In [91]:
data_overview(pa)

,Column,Data Type,Total Rows,Missing,% Missing,Unique Values,Unique Sample
0,SK_ID_PREV,int64,1670214,0,0.00,1670214,"[2030495, 2802425, 2523466, 2819243, 1784265]"
1,SK_ID_CURR,int64,1670214,0,0.00,338857,"[271877, 108129, 122040, 176158, 202054]"
2,NAME_CONTRACT_TYPE,object,1670214,0,0.00,4,"[Consumer loans, Cash loans, Revolving loans, ..."
3,AMT_ANNUITY,float64,1670214,0,0.00,357959,"[1730.43, 25188.615, 15060.735, 47041.335, 319..."
4,AMT_APPLICATION,float64,1670214,0,0.00,93885,"[17145.0, 607500.0, 112500.0, 450000.0, 337500.0]"
5,AMT_CREDIT,float64,1670214,1,0.00,86803,"[17145.0, 679671.0, 136444.5, 470790.0, 404055.0]"
6,AMT_GOODS_PRICE,float64,1670214,0,0.00,93885,"[17145.0, 607500.0, 112500.0, 450000.0, 337500.0]"
7,WEEKDAY_APPR_PROCESS_START,object,1670214,0,0.00,7,"[SATURDAY, THURSDAY, TUESDAY, MONDAY, FRIDAY]"
8,HOUR_APPR_PROCESS_START,int64,1670214,0,0.00,24,"[15, 11, 7, 9, 8]"
9,FLAG_LAST_APPL_PER_CONTRACT,object,1670214,0,0.00,2,"[Y, N]"
10,NFLAG_LAST_APPL_IN_DAY,int64,1670214,0,0.00,2,"[1, 0]"
11,NAME_CASH_LOAN_PURPOSE,object,1670214,0,0.00,25,"[XAP, XNA, Repairs, Everyday expenses, Car rep..."
12,NAME_CONTRACT_STATUS,object,1670214,0,0.00,4,"[Approved, Refused, Canceled, Unused offer]"
13,DAYS_DECISION,int64,1670214,0,0.00,2922,"[-73, -164, -301, -512, -781]"
14,NAME_PAYMENT_TYPE,object,1670214,0,0.00,4,"[Cash through the bank, XNA, Non-cash from you..."
15,CODE_REJECT_REASON,object,1670214,0,0.00,9,"[XAP, HC, LIMIT, CLIENT, SCOFR]"
16,NAME_TYPE_SUITE,object,1670214,0,0.00,8,"[Unknown, Unaccompanied, Spouse, partner, Fami..."
17,NAME_CLIENT_TYPE,object,1670214,0,0.00,4,"[Repeater, New, Refreshed, XNA]"
18,NAME_GOODS_CATEGORY,object,1670214,0,0.00,28,"[Mobile, XNA, Consumer Electronics, Constructi..."
19,NAME_PORTFOLIO,object,1670214,0,0.00,5,"[POS, Cash, XNA, Cards, Cars]"
20,NAME_PRODUCT_TYPE,object,1670214,0,0.00,3,"[XNA, x-sell, walk-in]"
21,CHANNEL_TYPE,object,1670214,0,0.00,8,"[Country-wide, Contact center, Credit and cash..."
22,SELLERPLACE_AREA,int64,1670214,0,0.00,2097,"[35, -1, 200, 83, 130]"
23,NAME_SELLER_INDUSTRY,object,1670214,0,0.00,11,"[Connectivity, XNA, Consumer electronics, Indu..."
24,CNT_PAYMENT,float64,1670214,0,0.00,49,"[12.0, 36.0, 24.0, 18.0, 54.0]"
25,NAME_YIELD_GROUP,object,1670214,0,0.00,5,"[middle, low_action, high, low_normal, XNA]"
26,PRODUCT_COMBINATION,object,1670214,346,0.02,17,"[POS mobile with interest, Cash X-Sell: low, C..."
27,DAYS_FIRST_DRAWING,float64,1670214,673065,40.30,2838,"[365243.0, -277.0, -265.0, -479.0, -332.0]"
28,DAYS_FIRST_DUE,float64,1670214,673065,40.30,2892,"[-42.0, -134.0, -271.0, -482.0, -654.0]"
29,DAYS_LAST_DUE_1ST_VERSION,float64,1670214,673065,40.30,4605,"[300.0, 916.0, 59.0, -152.0, -144.0]"
30,DAYS_LAST_DUE,float64,1670214,673065,40.30,2873,"[-42.0, 365243.0, -182.0, -144.0, -345.0]"
31,DAYS_TERMINATION,float64,1670214,673065,40.30,2830,"[-37.0, 365243.0, -177.0, -137.0, -334.0]"
32,NFLAG_INSURED_ON_APPROVAL,float64,1670214,673065,40.30,2,"[0.0, 1.0]"

In [92]:
pa.drop(columns=['DAYS_FIRST_DRAWING', 'DAYS_FIRST_DUE', 'DAYS_LAST_DUE_1ST_VERSION', 'DAYS_LAST_DUE', 'DAYS_TERMINATION', 'NFLAG_INSURED_ON_APPROVAL' ], inplace=True)

In [93]:
data_overview(pa)

,Column,Data Type,Total Rows,Missing,% Missing,Unique Values,Unique Sample
0,SK_ID_PREV,int64,1670214,0,0.00,1670214,"[2030495, 2802425, 2523466, 2819243, 1784265]"
1,SK_ID_CURR,int64,1670214,0,0.00,338857,"[271877, 108129, 122040, 176158, 202054]"
2,NAME_CONTRACT_TYPE,object,1670214,0,0.00,4,"[Consumer loans, Cash loans, Revolving loans, ..."
3,AMT_ANNUITY,float64,1670214,0,0.00,357959,"[1730.43, 25188.615, 15060.735, 47041.335, 319..."
4,AMT_APPLICATION,float64,1670214,0,0.00,93885,"[17145.0, 607500.0, 112500.0, 450000.0, 337500.0]"
5,AMT_CREDIT,float64,1670214,1,0.00,86803,"[17145.0, 679671.0, 136444.5, 470790.0, 404055.0]"
6,AMT_GOODS_PRICE,float64,1670214,0,0.00,93885,"[17145.0, 607500.0, 112500.0, 450000.0, 337500.0]"
7,WEEKDAY_APPR_PROCESS_START,object,1670214,0,0.00,7,"[SATURDAY, THURSDAY, TUESDAY, MONDAY, FRIDAY]"
8,HOUR_APPR_PROCESS_START,int64,1670214,0,0.00,24,"[15, 11, 7, 9, 8]"
9,FLAG_LAST_APPL_PER_CONTRACT,object,1670214,0,0.00,2,"[Y, N]"
10,NFLAG_LAST_APPL_IN_DAY,int64,1670214,0,0.00,2,"[1, 0]"
11,NAME_CASH_LOAN_PURPOSE,object,1670214,0,0.00,25,"[XAP, XNA, Repairs, Everyday expenses, Car rep..."
12,NAME_CONTRACT_STATUS,object,1670214,0,0.00,4,"[Approved, Refused, Canceled, Unused offer]"
13,DAYS_DECISION,int64,1670214,0,0.00,2922,"[-73, -164, -301, -512, -781]"
14,NAME_PAYMENT_TYPE,object,1670214,0,0.00,4,"[Cash through the bank, XNA, Non-cash from you..."
15,CODE_REJECT_REASON,object,1670214,0,0.00,9,"[XAP, HC, LIMIT, CLIENT, SCOFR]"
16,NAME_TYPE_SUITE,object,1670214,0,0.00,8,"[Unknown, Unaccompanied, Spouse, partner, Fami..."
17,NAME_CLIENT_TYPE,object,1670214,0,0.00,4,"[Repeater, New, Refreshed, XNA]"
18,NAME_GOODS_CATEGORY,object,1670214,0,0.00,28,"[Mobile, XNA, Consumer Electronics, Constructi..."
19,NAME_PORTFOLIO,object,1670214,0,0.00,5,"[POS, Cash, XNA, Cards, Cars]"
20,NAME_PRODUCT_TYPE,object,1670214,0,0.00,3,"[XNA, x-sell, walk-in]"
21,CHANNEL_TYPE,object,1670214,0,0.00,8,"[Country-wide, Contact center, Credit and cash..."
22,SELLERPLACE_AREA,int64,1670214,0,0.00,2097,"[35, -1, 200, 83, 130]"
23,NAME_SELLER_INDUSTRY,object,1670214,0,0.00,11,"[Connectivity, XNA, Consumer electronics, Indu..."
24,CNT_PAYMENT,float64,1670214,0,0.00,49,"[12.0, 36.0, 24.0, 18.0, 54.0]"
25,NAME_YIELD_GROUP,object,1670214,0,0.00,5,"[middle, low_action, high, low_normal, XNA]"
26,PRODUCT_COMBINATION,object,1670214,346,0.02,17,"[POS mobile with interest, Cash X-Sell: low, C..."

In [94]:
pa['PRODUCT_COMBINATION'] = pa['PRODUCT_COMBINATION'].fillna(pa['PRODUCT_COMBINATION'].mode()[0])

In [95]:
data_overview(pa)

,Column,Data Type,Total Rows,Missing,% Missing,Unique Values,Unique Sample
0,SK_ID_PREV,int64,1670214,0,0.00,1670214,"[2030495, 2802425, 2523466, 2819243, 1784265]"
1,SK_ID_CURR,int64,1670214,0,0.00,338857,"[271877, 108129, 122040, 176158, 202054]"
2,NAME_CONTRACT_TYPE,object,1670214,0,0.00,4,"[Consumer loans, Cash loans, Revolving loans, ..."
3,AMT_ANNUITY,float64,1670214,0,0.00,357959,"[1730.43, 25188.615, 15060.735, 47041.335, 319..."
4,AMT_APPLICATION,float64,1670214,0,0.00,93885,"[17145.0, 607500.0, 112500.0, 450000.0, 337500.0]"
5,AMT_CREDIT,float64,1670214,1,0.00,86803,"[17145.0, 679671.0, 136444.5, 470790.0, 404055.0]"
6,AMT_GOODS_PRICE,float64,1670214,0,0.00,93885,"[17145.0, 607500.0, 112500.0, 450000.0, 337500.0]"
7,WEEKDAY_APPR_PROCESS_START,object,1670214,0,0.00,7,"[SATURDAY, THURSDAY, TUESDAY, MONDAY, FRIDAY]"
8,HOUR_APPR_PROCESS_START,int64,1670214,0,0.00,24,"[15, 11, 7, 9, 8]"
9,FLAG_LAST_APPL_PER_CONTRACT,object,1670214,0,0.00,2,"[Y, N]"
10,NFLAG_LAST_APPL_IN_DAY,int64,1670214,0,0.00,2,"[1, 0]"
11,NAME_CASH_LOAN_PURPOSE,object,1670214,0,0.00,25,"[XAP, XNA, Repairs, Everyday expenses, Car rep..."
12,NAME_CONTRACT_STATUS,object,1670214,0,0.00,4,"[Approved, Refused, Canceled, Unused offer]"
13,DAYS_DECISION,int64,1670214,0,0.00,2922,"[-73, -164, -301, -512, -781]"
14,NAME_PAYMENT_TYPE,object,1670214,0,0.00,4,"[Cash through the bank, XNA, Non-cash from you..."
15,CODE_REJECT_REASON,object,1670214,0,0.00,9,"[XAP, HC, LIMIT, CLIENT, SCOFR]"
16,NAME_TYPE_SUITE,object,1670214,0,0.00,8,"[Unknown, Unaccompanied, Spouse, partner, Fami..."
17,NAME_CLIENT_TYPE,object,1670214,0,0.00,4,"[Repeater, New, Refreshed, XNA]"
18,NAME_GOODS_CATEGORY,object,1670214,0,0.00,28,"[Mobile, XNA, Consumer Electronics, Constructi..."
19,NAME_PORTFOLIO,object,1670214,0,0.00,5,"[POS, Cash, XNA, Cards, Cars]"
20,NAME_PRODUCT_TYPE,object,1670214,0,0.00,3,"[XNA, x-sell, walk-in]"
21,CHANNEL_TYPE,object,1670214,0,0.00,8,"[Country-wide, Contact center, Credit and cash..."
22,SELLERPLACE_AREA,int64,1670214,0,0.00,2097,"[35, -1, 200, 83, 130]"
23,NAME_SELLER_INDUSTRY,object,1670214,0,0.00,11,"[Connectivity, XNA, Consumer electronics, Indu..."
24,CNT_PAYMENT,float64,1670214,0,0.00,49,"[12.0, 36.0, 24.0, 18.0, 54.0]"
25,NAME_YIELD_GROUP,object,1670214,0,0.00,5,"[middle, low_action, high, low_normal, XNA]"
26,PRODUCT_COMBINATION,object,1670214,0,0.00,17,"[POS mobile with interest, Cash X-Sell: low, C..."

In [ ]:
import os
ip.to_csv(r'C:\Users\ASUS\OneDrive\Documents\Rakamin\Project\Data Set\Cleaned Data\installments_payments_cleaned.csv', index=False)

In [96]:
b.to_csv(r'C:\Users\ASUS\OneDrive\Documents\Rakamin\Project\Data Set\Cleaned Data\bureau_cleaned.csv', index=False)

In [ ]:
import os



b.to_csv(r'C:\Users\ASUS\OneDrive\Documents\Rakamin\Project\Data Set\Cleaned Data\bureau_cleaned.csv', index=False)
ccb.to_csv(r'C:\Users\ASUS\OneDrive\Documents\Rakamin\Project\Data Set\Cleaned Data\credit_card_balance_cleaned.csv', index=False)
ip.to_csv(r'C:\Users\ASUS\OneDrive\Documents\Rakamin\Project\Data Set\Cleaned Data\installments_payments_cleaned.csv', index=False)
pcb.to_csv(r'C:\Users\ASUS\OneDrive\Documents\Rakamin\Project\Data Set\Cleaned Data\POS_CASH_balance_cleaned.csv', index=False)
pa.to_csv(r'C:\Users\ASUS\OneDrive\Documents\Rakamin\Project\Data Set\Cleaned Data\previous_application_cleaned.csv', index=False)